"""add user email and password

Revision ID: 6fd8fac02883
Revises: 6d2f94baf4b7
Create Date: 2026-02-20 11:43:47.679075

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6fd8fac02883"
down_revision: Union[str, None] = "6d2f94baf4b7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    
    has_email = False
    has_password = False
    
    columns = inspector.get_columns('users')
    for c in columns:
        if c['name'] == 'email':
            has_email = True
        if c['name'] == 'password_hash':
            has_password = True

    if not has_email:
        op.add_column("users", sa.Column("email", sa.String(), nullable=True))
        op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
        
    if not has_password:
        op.add_column("users", sa.Column("password_hash", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_column("users", "password_hash")
    op.drop_column("users", "email")
    # ### end Alembic commands ###
